### ISSUE TITLE
I have a problem with evaluating BIG. "No such file or directory: 'data/big/coarse/deeplab'"

### ISSUE THREAD

**Issue by AppleJoker94** [MengyuWang826/SegRefiner#14]
I found the paper fascinating and am grateful for the amazing work.

I am in the process of testing HR-SegRefiner. 
I have generated coarse masks using `python scripts/gen_coarse_masks_hr.py` and have proceeded with training using `python tools/train.py configs/segrefiner/segrefiner_hr.py.`

However, when I entered `python tools/test.py configs/segrefiner/segrefiner_big.py checkpoints/segrefiner_hr_latest.pth --out_dir ./test_model_name` for evaluation, the following problem occurred. Do I need to download the data and create a folder path?

```
(segrefiner) sj@sjpc:~/sj_ws/SegRefiner_main$ python tools/test.py configs/segrefiner/segrefiner_big.py checkpoints/segrefiner_hr_latest.pth --out_dir ./test_model_name
/home/sj/anaconda3/envs/segrefiner/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/sj/anaconda3/envs/segrefiner/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/sj/sj_ws/SegRefiner_main/mmdet/datasets/big.py", line 41, in __init__
    self.data_infos = self.load_datas(self.data_root)
  File "/home/sj/sj_ws/SegRefiner_main/mmdet/datasets/big.py", line 55, in load_datas
    all_files = os.listdir(data_root)
FileNotFoundError: [Errno 2] No such file or directory: 'data/big/coarse/deeplab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 184, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/sj/sj_ws/SegRefiner_main/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/sj/anaconda3/envs/segrefiner/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: BigDataset: [Errno 2] No such file or directory: 'data/big/coarse/deeplab'
```

**Comment by AppleJoker94** [comment]
I download author's masks and run complete!

**Comment by achyutduggal** [comment]
Hi, can you share the link from where can I get the masks, been trying to run inference, getting the same error
